[project]
name = "babeltower-eval"
version = "0.1.0"
description = "Eval pass@k for babeltower"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "datasets>=3.1.0",
    "loguru>=0.7.3",
    "numpy>=1.24.4",
    "openai>=1.72.0",
    "pandas>=2.0.3",
    "tenacity>=9.0.0",
]
